### ISSUE TITLE
Exception in inputworker (can't add a new key into hash during iteration)

### ISSUE THREAD

**Issue by cvicente** [logstash-plugins/logstash-codec-netflow#53]
I have a logstash instance receiving IPFIX from multiple Juniper routers. I'm using:

Ubuntu 14.04
logstash 1:2.3.4-1
logstash-codec-netflow 2.1.1

Once every few days I see that the UDP error counters on the system goes up and logstash stops processing flows from one of the routers. The solution is to restart logstash. The following error seems related:

```
{:timestamp=>"2016-10-20T12:41:26.899000+0000", :message=>"Exception in inputworker", "exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:992:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow/util.rb:268:in `ttl'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow/util.rb:242:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow.rb:362:in `decode_ipfix'", "org/jruby/RubyKernel.java:1242:in `catch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow.rb:334:in `decode_ipfix'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.1/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.1/lib/bindata/array.rb:208:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow.rb:333:in `decode_ipfix'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow.rb:163:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.1/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.1/lib/bindata/array.rb:208:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.1.1/lib/logstash/codecs/netflow.rb:162:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:96:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:73:in `udp_listener'"], :level=>:error}
{:timestamp=>"2016-10-20T12:41:26.921000+0000", :message=>"Invalid netflow packet received (value '0' not as expected for obj.records[1].flowset_id)", :level=>:warn}
```

I would appreciate any pointers. Thank you.

**Comment by jorritfolmer** [comment]
To start with the last one, it is a warning indicating receipt of an invalid IPFIX packet. It will drop it, and continue. (Flowset_id cannot be 0, see 3.3.2 from RFC7011 if you're interested).
The warning also came slightly later than the exception, suggesting that it was handled by another input worker thread that was non-crashed.

I've had a similar issue reported to me, privately unfortunately, about Juniper routers and invalid flowset_id's. Miraculously also in combination with `can't add a new key into hash during iteration`.

Which brings me to the input worker exception. I suggest that you try to lower the `workers` parameter for the UDP input plugin to 1. It defaults to 2. I have a feeling the Volatile Hash construct we use in util.rb isn't thread safe, since it is complaining about being modified while accessing.

Could you try that and report back? Also, can you tell me a little bit about your environment in terms of numbers? How many Junipers? Flows per hour? I'd like to do create a load test to reproduce things like this, and like to know what I should aim for, when time permits.

**Comment by cvicente** [comment]
@jorritfolmer Thank you for the info. I will test the workers setting and report back.

**Comment by jorritfolmer** [comment]
Any update on this?

**Comment by cvicente** [comment]
Greetings. I reduced the workers parameter in the UDP plugin 13 days ago and have not seen that error appear yet. I'd like to give it another couple of weeks to be 100% sure that it solved that problem. Thank you.

**Comment by jorritfolmer** [comment]
Ok thanks! Seems like good news!
