### ISSUE TITLE
Codec ignores netflow records containing template + data

### ISSUE THREAD

**Issue by bluefangs** [logstash-plugins/logstash-codec-netflow#95]
- Version: **3.6.0**
- Operating System: **Ubuntu 16.04**
- Config File:  **All files pertaining to logstash config is located** [here](https://github.com/robcowart/elastiflow/tree/master/logstash).
- Sample data: **Attached pcap file**
- Steps to Reproduce:

This issue is on the back of https://github.com/logstash-plugins/logstash-codec-netflow/issues/92 which is now closed. Unfortunately, it has not fixed this particular problem.

I've noticed that if a netflow record has both template-data and data in the same flow, it does not get picked up by the logstash plugin.

In summary:

If the netflow data is like below (generated by pfSense), it gets picked up by the plugin.
```
[data-template:1024] 
[data: 1024]
[data: 1024]
```

But if the template data is of the below, it does not get picked up by the plugin.
```
[data-template: 256] [data:256] [data:256]
[data-template: 256] [data:256] [data:256]
```
![selection_006](https://user-images.githubusercontent.com/19926675/31161121-aa815cf2-a8f2-11e7-8e5f-03147696c0b3.png)

I've attached the relevant pcap file.
I'd appreciate some help with figuring out why this is so or what can be done to address such a scenario.

[not-working-pcap.pcap.tar.gz](https://github.com/logstash-plugins/logstash-codec-netflow/files/1355781/not-working-pcap.pcap.tar.gz)

**Comment by bluefangs** [comment]
Closing this issue as we managed to find out a root cause.

**Comment by jorritfolmer** [comment]
Good to hear!
Can you share what you found out?

**Comment by bluefangs** [comment]
There was no issue with the netflow records and templates as such. Infact it was [this](https://discuss.elastic.co/t/logstash-codec-netflow-does-not-accept-netflow-packets-coming-from-a-different-ip-subnet/102950)... which I still don't know why.

Once we managed to bring both the collector and logstach host under the same subnet, things started working. Would you happen to have any clue about this?

**Comment by phixit** [comment]
Sounds like a problem I ran into before... If you have multiple interfaces and can see the packets coming in on one interface (tcpdump/wireshark), but you do not have a route back to the source on that interface, the packet is not passed down to application level.

You would expect since you are receive only and tcpdump can see it then the application can.
This has to do with the need to be able to send unreachable messages (even if you don't).

add a route to your source ,and the listener starts working.

Let us know if that corrects your case as well
